### ISSUE TITLE
Indigo Support

### ISSUE THREAD

**Issue by johngroves** [bsb808/kingfisher_gazebo#2]
I've just started working with this plugin, but I'm getting the following error when attempting to launch a gazebo world:

`xacro.XacroException: Property wasn't defined: u'min_inertia'`

I noticed the recent changes to the urdf files, are these breaking changes that drop Indigo support?

Thanks!

**Comment by johngroves** [comment]
Just found indigo-devel!

**Comment by bsb808** [comment]
John,

My apologies for the confusion.  I was messing around with support for Kinetic and found that there were some compatibility issues with the way xacro is used.  It doesn't help that Clearpath isn't supporting any of the underlying bits (msgs, description, etc.) past Indigo.

This is something we are semi-actively working on, so there may be changes moving forward, will try to keep a reasonably stable main branch for Indigo and Kinetic, but...

Please send pull requests if you find any issues or have anything to add - we are a small community!

Brian

**Comment by johngroves** [comment]
Brian, no problem, thanks for the hard work that has been put into this!
I'm working on building a USV, and will contribute where I can!
